# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aXK0YKSKS44esHEn86BF20dfX2c7o7ih
"""

#Question 1Write a Python program to count the number of characters (character frequency) in a stringExamble: ('google.com') =>  {'g': 2, 'o': 3, 'l': 1, 'e': 1, '.': 1, 'c': 1, 'm': 1}
#Examble: ('google.com') =>  {'g': 2, 'o': 3, 'l': 1, 'e': 1, '.': 1, 'c': 1, 'm': 1}

s="google.com"
c={}
for i in s:
    if i in c:
      c[i]+=1
    else:
          c[i]=1
print ("the coumt is",c)



#Question 2 Write a Python program to get a string from a given string where all occurrences of its first char have been changed to '$', except the first char itself.
#Examble => 'restart' => 'resta$t'    'google'  => 'goo$le'
def change_char (str1) :
    char = str1[0]
    str1 = str1.replace (char, '$')
    str1 = char + str1 [1 : ]
    return str1

print ("the result after replacement is :\n",change_char ('nananana'))

# Question 3 :Write a Python program to get a single string from two given strings, separated by a space and swap the first two characters of each string.
#Examble : 'abc', 'xyz' => xyc abz
str1 = input("Please Enter First String : ")
str2 =input("Please Enter Second String : ")

x=str1[0:2]

str1=str1.replace(str1[0:2],str2[0:2])

str2=str2.replace(str2[0:2],x)

print("Your two strings after replacment is :- ",str1 +" " +str2)

# Question 4:Write a Python program to add 'ing' at the end of a given string (length should be at least 3). If the given string already ends with 'ing' then add 'ly' instead. If the string length of the given string is less than 3, leave it unchanged.
#Examble => ab => ab
        #=> abc => abcing 
        #=> string => stringly
a = input('Enter a string  YA GAMIL')
b   = a[-3:]
if(a[-3:] == 'ing'):
    b = a +'ly'
elif(len(b) <3):
    print(b)
else:
    b =a+'ing'
print(b)

# Question 5:write a Python script to display the various Date Time formats.

#a) Current date and time
#b) Current year
#c) Month of year
#d) Week number of the year
#e) Weekday of the week
#f) Day of year
#g) Day of the month
#h) Day of week
#Solution=>
#import time
#import datetime
import time
import datetime
from datetime import date
today=date.today()
print (today.ctime())
print (today.year)
print (today.day)
print (today.month)
print (datetime.date.today().strftime("%W")) #week of year ##STRING FORMAT TIME
print (datetime.date.today().strftime("%j"))# day of year
print (datetime.date.today().strftime("%d"))# day of the month
print (datetime.date.today().strftime("%A"))# day of the week

print (today)

# Question 6: write a Python program to print yesterday, today, tomorrow.
#Yesterday :  2020-01-17 Today :  2020-01-18    Tomorrow :  2020-01-19
#Solution=>mport datetime
import datetime 
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)

# Question 7: Write a Python program to add 5 seconds with the current time.
import datetime
x= datetime.datetime.now()
y = x + datetime.timedelta(0,5)
print(x.time())
print(y.time())

# Question 8:Write a Python program to convert Year/Month/Day to Day of Year.
import datetime
today = datetime.datetime.now()
day_of_year = (today - datetime.datetime(today.year, 1, 1)).days + 1
print(day_of_year)

# Question 9 Write a Python program to get current time in milliseconds.
import time
milli_sec = int(round(time.time() * 1000))
print(milli_sec)
import time

# Question 10 Write a Python program to get week number.
import datetime
print(datetime.date(2022, 4, 18).isocalendar()[1])

# Question 11 :Write a Python program that matches a string that has an 'a' followed by anything, ending in 'b'.
import re


s=input("Enter a string:")

x=re.findall("a.+b$",s)
print(x)

# Question 12 :Write a Python program to calculate the area of a trapezoid.شبه منحرف

height = float(input("Height of trapezoid: "))
base_1 = float(input(' Enter Ya helw Base one value: '))
base_2 = float(input(' Enter Base two value We khalas: '))
area = ((base_1 + base_2) / 2) * height
print("Area is:", area)